### ISSUE TITLE
Duplicate logging of (most) JCasC configuration entries during startup

### ISSUE THREAD

**Issue by reinholdfuereder** [jenkinsci/configuration-as-code-plugin#899] opened 2019-05-29 05:12 UTC
### Your checklist for this issue

- [ x ] Jenkins version: 2.179 (latest)

- [ x ] Plugin version: JCasC 1.17 (latest)

- [ x ] OS: Linux

### Description

During Jenkins (master) startup almost each JCasC YAML file configuration entry is logged exactly twice:
```
2019-05-29 04:36:25.363+0000 [id=1]     INFO    o.e.j.s.handler.ContextHandler#doStart: Started w.@355e34c7{Jenkins v2.179,/,file:///var/cache/jenkins/war/,AVAILABLE}{/var/cache/jenkins/war}
2019-05-29 04:36:25.394+0000 [id=1]     INFO    o.e.j.server.AbstractConnector#doStart: Started ServerConnector@124c278f{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-05-29 04:36:25.394+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: Started @2043ms
2019-05-29 04:36:25.396+0000 [id=23]    INFO    winstone.Logger#logInternal: Winstone Servlet Engine v4.0 running: controlPort=disabled
2019-05-29 04:36:27.162+0000 [id=31]    INFO    jenkins.InitReactorRunner$1#onAttained: Started initialization
2019-05-29 04:36:27.699+0000 [id=32]    INFO    jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2019-05-29 04:36:42.889+0000 [id=30]    INFO    jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2019-05-29 04:36:43.597+0000 [id=34]    INFO    h.ExtensionFinder$GuiceFinder$FaultTolerantScope$1#error: Failed to instantiate optional component hudson.plugins.build_timeout.operations.AbortAndRestartOperation$DescriptorImpl; skipping
2019-05-29 04:36:45.760+0000 [id=36]    INFO    jenkins.InitReactorRunner$1#onAttained: Started all plugins
2019-05-29 04:36:45.789+0000 [id=33]    INFO    jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2019-05-29 04:36:46.881+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class jenkins.security.plugins.ldap.LDAPConfiguration.server = ***
2019-05-29 04:36:46.882+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class jenkins.security.plugins.ldap.LDAPConfiguration.rootDN = ***
2019-05-29 04:36:46.884+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class jenkins.security.plugins.ldap.LDAPConfiguration.managerDN = ***
2019-05-29 04:36:46.885+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class jenkins.security.plugins.ldap.LDAPConfiguration.managerPasswordSecret = ****
2019-05-29 04:36:46.886+0000 [id=32]    WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class jenkins.security.plugins.ldap.LDAPConfiguration#extraEnvVars: type is abstract but not Describable.
2019-05-29 04:36:46.887+0000 [id=32]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting jenkins.security.plugins.ldap.LDAPConfiguration@38f043bc.groupSearchBase = ***
2019-05-29 04:36:46.888+0000 [id=32]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting jenkins.security.plugins.ldap.LDAPConfiguration@38f043bc.userSearchBase = ***
2019-05-29 04:36:46.888+0000 [id=32]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting jenkins.security.plugins.ldap.LDAPConfiguration@38f043bc.userSearch = ***
2019-05-29 04:36:46.889+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class hudson.security.LDAPSecurityRealm.configurations = [{}]
2019-05-29 04:36:46.889+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class hudson.security.LDAPSecurityRealm$CacheConfiguration.size = 50
2019-05-29 04:36:46.890+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class hudson.security.LDAPSecurityRealm$CacheConfiguration.ttl = 60
2019-05-29 04:36:46.890+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class hudson.security.LDAPSecurityRealm.cache = {}
2019-05-29 04:36:46.975+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabApiTokenImpl.scope = GLOBAL
2019-05-29 04:36:46.975+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabApiTokenImpl.id = ***
2019-05-29 04:36:46.976+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabApiTokenImpl.description = ***
2019-05-29 04:36:46.976+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabApiTokenImpl.apiToken = ****
2019-05-29 04:36:46.981+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.scope = GLOBAL
2019-05-29 04:36:46.981+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.id = ***
2019-05-29 04:36:46.981+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.description = ***
2019-05-29 04:36:46.981+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.username = ***
2019-05-29 04:36:46.981+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.password = ***
2019-05-29 04:36:46.984+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.scope = GLOBAL
2019-05-29 04:36:46.984+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.id = ***
2019-05-29 04:36:46.985+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.description = ***
2019-05-29 04:36:46.985+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.username = ***
2019-05-29 04:36:46.985+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.password = ***
2019-05-29 04:36:46.986+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.domains.DomainCredentials.credentials = [{gitLabApiTokenImpl={}}, {usernamePassword={}}, {usernamePassword={}}]
2019-05-29 04:36:47.539+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.name = ***
2019-05-29 04:36:47.540+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.url = ***
2019-05-29 04:36:47.540+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.apiTokenId = ***
2019-05-29 04:36:47.540+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.clientBuilderId = autodetect
2019-05-29 04:36:47.540+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.ignoreCertificateErrors = false
2019-05-29 04:36:47.541+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.connectionTimeout = 10
2019-05-29 04:36:47.541+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.readTimeout = 10
2019-05-29 04:36:47.649+0000 [id=32]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting hudson.model.Hudson@f306fd9.systemMessage =
2019-05-29 04:36:47.650+0000 [id=32]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting hudson.model.Hudson@f306fd9.numExecutors = 15
2019-05-29 04:36:47.653+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class jenkins.security.plugins.ldap.LDAPConfiguration.server = ***
2019-05-29 04:36:47.653+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class jenkins.security.plugins.ldap.LDAPConfiguration.rootDN = ***
2019-05-29 04:36:47.653+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class jenkins.security.plugins.ldap.LDAPConfiguration.managerDN = ***
2019-05-29 04:36:47.654+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class jenkins.security.plugins.ldap.LDAPConfiguration.managerPasswordSecret = ****
2019-05-29 04:36:47.654+0000 [id=32]    WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class jenkins.security.plugins.ldap.LDAPConfiguration#extraEnvVars: type is abstract but not Describable.
2019-05-29 04:36:47.655+0000 [id=32]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting jenkins.security.plugins.ldap.LDAPConfiguration@4d0a2fc0.groupSearchBase = ***
2019-05-29 04:36:47.655+0000 [id=32]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting jenkins.security.plugins.ldap.LDAPConfiguration@4d0a2fc0.userSearchBase = ***
2019-05-29 04:36:47.655+0000 [id=32]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting jenkins.security.plugins.ldap.LDAPConfiguration@4d0a2fc0.userSearch = ***
2019-05-29 04:36:47.656+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class hudson.security.LDAPSecurityRealm.configurations = [{}]
2019-05-29 04:36:47.656+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class hudson.security.LDAPSecurityRealm$CacheConfiguration.size = 50
2019-05-29 04:36:47.656+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class hudson.security.LDAPSecurityRealm$CacheConfiguration.ttl = 60
2019-05-29 04:36:47.657+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class hudson.security.LDAPSecurityRealm.cache = {}
2019-05-29 04:36:47.658+0000 [id=32]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting hudson.model.Hudson@f306fd9.securityRealm = hudson.security.LDAPSecurityRealm@7dd27213
2019-05-29 04:36:49.543+0000 [id=32]    INFO    o.s.c.s.AbstractApplicationContext#prepareRefresh: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@1dfe74ee: display name [Root WebApplicationContext]; startup date [Wed May 29 06:36:49 CEST 2019]; root of context hierarchy
2019-05-29 04:36:49.544+0000 [id=32]    INFO    o.s.c.s.AbstractApplicationContext#obtainFreshBeanFactory: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@1dfe74ee]: org.springframework.beans.factory.support.DefaultListableBeanFactory@32aae859
2019-05-29 04:36:49.557+0000 [id=32]    INFO    o.s.b.f.s.DefaultListableBeanFactory#preInstantiateSingletons: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@32aae859: defining beans [ldapUserSearch,authenticationManager,bindAuthenticator,authoritiesPopulator,initialDirContextFactory]; root of factory hierarchy
2019-05-29 04:36:49.580+0000 [id=32]    INFO    o.a.l.DefaultInitialDirContextFactory#setProviderUrl:  URL '***/***', root DN is '***'
2019-05-29 04:36:49.830+0000 [id=32]    INFO    o.s.c.s.AbstractApplicationContext#prepareRefresh: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@2134e916: display name [Root WebApplicationContext]; startup date [Wed May 29 06:36:49 CEST 2019]; root of context hierarchy
2019-05-29 04:36:49.830+0000 [id=32]    INFO    o.s.c.s.AbstractApplicationContext#obtainFreshBeanFactory: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@2134e916]: org.springframework.beans.factory.support.DefaultListableBeanFactory@6729344a
2019-05-29 04:36:49.831+0000 [id=32]    INFO    o.s.b.f.s.DefaultListableBeanFactory#preInstantiateSingletons: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@6729344a: defining beans [filter,legacy]; root of factory hierarchy
2019-05-29 04:36:49.921+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabApiTokenImpl.scope = GLOBAL
2019-05-29 04:36:49.921+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabApiTokenImpl.id = ***
2019-05-29 04:36:49.921+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabApiTokenImpl.description = ***
2019-05-29 04:36:49.922+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabApiTokenImpl.apiToken = ****
2019-05-29 04:36:49.924+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.scope = GLOBAL
2019-05-29 04:36:49.924+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.id = ***
2019-05-29 04:36:49.924+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.description = ***
2019-05-29 04:36:49.924+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.username = ***
2019-05-29 04:36:49.925+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.password = ***
2019-05-29 04:36:49.927+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.scope = GLOBAL
2019-05-29 04:36:49.927+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.id = ***
2019-05-29 04:36:49.927+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.description = ***
2019-05-29 04:36:49.927+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.username = ***
2019-05-29 04:36:49.927+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.password = ***
2019-05-29 04:36:49.928+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.cloudbees.plugins.credentials.domains.DomainCredentials.credentials = [{gitLabApiTokenImpl={}}, {usernamePassword={}}, {usernamePassword={}}]
2019-05-29 04:36:49.929+0000 [id=32]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting com.cloudbees.plugins.credentials.SystemCredentialsProvider@339252af.domainCredentials = [com.cloudbees.plugins.credentials.domains.DomainCredentials@37bc7c9b]
2019-05-29 04:36:49.937+0000 [id=32]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting com.cloudbees.plugins.credentials.GlobalCredentialsConfiguration@39d5c3c4.system = com.cloudbees.plugins.credentials.SystemCredentialsProvider@339252af
2019-05-29 04:36:50.434+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.name = ***
2019-05-29 04:36:50.434+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.url = ***
2019-05-29 04:36:50.434+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.apiTokenId = ***
2019-05-29 04:36:50.434+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.clientBuilderId = autodetect
2019-05-29 04:36:50.434+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.ignoreCertificateErrors = false
2019-05-29 04:36:50.434+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.connectionTimeout = 10
2019-05-29 04:36:50.435+0000 [id=32]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.readTimeout = 10
2019-05-29 04:36:50.435+0000 [id=32]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig@1bfd3c17.connections = [com.dabsquared.gitlabjenkins.connection.GitLabConnection@5a80bd89]
2019-05-29 04:36:50.442+0000 [id=32]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting jenkins.model.GlobalConfigurationCategory$Unclassified@3cb5e91b.gitLabConnectionConfig = com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig@1bfd3c17
2019-05-29 04:36:50.443+0000 [id=34]    INFO    jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
2019-05-29 04:36:50.451+0000 [id=35]    INFO    j.util.groovy.GroovyHookScript#execute: Executing /var/lib/jenkins/init.groovy.d/00-start-in-quiet-mode.groovy
2019-05-29 04:36:50.493+0000 [id=68]    INFO    hudson.model.AsyncPeriodicWork$1#run: Started Download metadata
2019-05-29 04:36:50.532+0000 [id=68]    INFO    hudson.model.AsyncPeriodicWork$1#run: Finished Download metadata. 32 ms
...
2019-05-29 04:36:50.872+0000 [id=31]    INFO    o.s.c.s.AbstractApplicationContext#prepareRefresh: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@3e8a8e03: display name [Root WebApplicationContext]; startup date [Wed May 29 06:36:50 CEST 2019]; root of context hierarchy
2019-05-29 04:36:50.873+0000 [id=31]    INFO    o.s.c.s.AbstractApplicationContext#obtainFreshBeanFactory: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@3e8a8e03]: org.springframework.beans.factory.support.DefaultListableBeanFactory@360082ae
2019-05-29 04:36:50.874+0000 [id=31]    INFO    o.s.b.f.s.DefaultListableBeanFactory#preInstantiateSingletons: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@360082ae: defining beans [filter,legacy]; root of factory hierarchy
...
2019-05-29 04:37:01.488+0000 [id=35]    INFO    jenkins.InitReactorRunner$1#onAttained: Completed initialization
2019-05-29 04:37:01.544+0000 [id=22]    INFO    hudson.WebAppMain$3#run: Jenkins is fully up and running
```

The only exceptions (that are logged just the expected single time) seem to be: `systemMessage`, `numExecutors`
... although some of the `i.jenkins.plugins.casc.Attribute#setValue` logs are also only there once.

Please mind that in my "jenkins.yaml" file there are:
* really just one `ldap` configuration within `securityRealm`
* in `credentials > system` there is one `gitLabApiTokenImpl` and two `usernamePassword`
* in `unclassified` there is one `gitLabConnectionConfig` (with one entry in `connections`)

**Comment by timja** [comment] 2019-05-29 06:32
Please provide your config file...

**Comment by reinholdfuereder** [comment] 2019-05-29 11:21
"jenkins.yaml":
```
jenkins:
  systemMessage: ""
  numExecutors: ***

  securityRealm:
    ldap:
      cache:
        size: 50
        ttl: 60
      configurations:
        - server: ***
          rootDN: ***
          managerDN: ***
          managerPasswordSecret: ***
          userSearchBase: ***
          userSearch: ***
          groupSearchBase: ***

credentials:
  system:
    domainCredentials:
    - credentials:
      - gitLabApiTokenImpl:
          scope: GLOBAL
          id: ***
          apiToken: ***
          description: ***
      - usernamePassword:
          scope: GLOBAL
          id: ***
          username: ***
          password: ***
          description: ***
      - usernamePassword:
          scope: GLOBAL
          id: ***
          username: ***
          password: ***
          description: ***

unclassified:
  gitLabConnectionConfig:
    # Not yet released: see https://github.com/jenkinsci/configuration-as-code-plugin/issues/676 and https://github.com/jenkinsci/gitlab-plugin/pull/866
    #useAuthenticatedEndpoint: false
    connections:
    - apiTokenId: ***
      name: ***
      url: ***
      clientBuilderId: ***
      connectionTimeout: ***
      readTimeout: ***
      ignoreCertificateErrors: ***
```

**Comment by casz** [comment] 2019-08-25 16:02
I believe this is by design 😓

before running [`configureWith`] we execute [`checkWith`] which is properly the cause of duplicate logs.

I wonder if there is a way we can reduce the log level temporarily for [`checkWith`]
WDYT @oleg-nenashev @timja 

[`configureWith`]: https://github.com/jenkinsci/configuration-as-code-plugin/blob/817168b801a229dc64a4460025b69ea4f203eeea/plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java#L687
[`checkWith`]: https://github.com/jenkinsci/configuration-as-code-plugin/blob/817168b801a229dc64a4460025b69ea4f203eeea/plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java#L703

**Comment by casz** [comment] 2019-08-25 19:49
Actually, this should be fixed in a [recent version] due to a reduction in [log level].

[recent version]: https://github.com/jenkinsci/configuration-as-code-plugin/releases/tag/configuration-as-code-1.26
[log level]: https://github.com/jenkinsci/configuration-as-code-plugin/pull/975

**Closed** 2019-08-25 19:54 UTC
Labels: bug

**Comment by reinholdfuereder** [comment] 2019-08-26 04:03
@casz Yes, you are right: it is worked around and I can perfectly live with that. Thanks for taking care...
