### ISSUE TITLE
[Feature] - Load yaml from source code control (Git) with credentials

### ISSUE THREAD

**Issue by stunney** [jenkinsci/configuration-as-code-plugin#879] opened 2019-05-07 20:53 UTC
As an administrator who likes to have history for configuration of his Jenkins servers I would like the ability to have multiple users, audit, and rollback capabilities for my jenkins.yaml file.

The ability to sync with a protected git@ or https:// and use an ssh key would be a great way to accomplish this.

**Comment by casz** [comment] 2019-05-08 02:44
Duplicate of #273

**Closed by casz** 2019-05-08 02:44 UTC
Labels: feature
