### ISSUE TITLE
Credentials cannot be configured on fresh install

### ISSUE THREAD

**Issue by BrianSidebotham** [jenkinsci/configuration-as-code-plugin#1208] opened 2019-11-22 15:22 UTC
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version

- [x] Plugin version

- [x] OS

### Description

configuration-as-code plugin fails to install using the `jenkins-cli` after the credentials plugin has been installed.

os version: CentOS 7

jenkins version: 2.205-1.1 from http://pkg.jenkins.io/redhat

credentials plugin version: 2.3.0
configuration-as-code plugin version: 1.33

jenkins yaml contains:

```yaml
credentials:
    system:
        domainCredentials:
            - credentials:
                - usernamePassword:
                    scope: GLOBAL
                    id: "Description"
                    username: someUsername
                    password: somePassword
                    description: "Description of credential"
```

Error stacktrace:

```
2019-11-22 14:53:04.549+0000 [id=86]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed ConfigurationAsCode.init
io.jenkins.plugins.casc.ConfiguratorException: No configurator for root element <credentials>
        at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:691)
        at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:727)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:712)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:593)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:281)
        at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:273)
Caused: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

```
2019-11-22 14:53:04.551+0000 [id=74]    SEVERE  h.model.UpdateCenter$DownloadJob#run: Failed to install configuration-as-code
io.jenkins.plugins.casc.ConfiguratorException: No configurator for root element <credentials>
        at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:691)
        at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:727)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:712)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:593)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:281)
        at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:273)
Caused: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Caused: org.jvnet.hudson.reactor.ReactorException
        at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
        at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
        at hudson.PluginManager.start(PluginManager.java:967)
        at hudson.PluginManager.dynamicLoad(PluginManager.java:935)
Caused: java.io.IOException: Failed to install configuration-as-code plugin
        at hudson.PluginManager.dynamicLoad(PluginManager.java:942)
        at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2082)
Caused: java.io.IOException: Failed to dynamically deploy this plugin
        at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2086)
        at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1773)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:111)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by casz** [comment] 2019-11-22 15:24
You haven't installed credentials plugin

**Comment by casz** [comment] 2019-11-22 15:26
Or plugin isn't activated

**Comment by BrianSidebotham** [comment] 2019-11-22 15:27
Yes I have. That's why I've put the credentials plugin version above. All done through the `jenkins-cli`.

`java -jar jenkins-cli.jar -s http://localhost:8080 -http -auth userName:userPassword install-plugin credentials -deploy -restart`

**Comment by BrianSidebotham** [comment] 2019-11-22 15:33
A complete list is available:

```
# java -jar jenkins-cli.jar -s http://localhost:8080/ list-plugins
trilead-api                        Trilead API Plugin                              1.0.5
jaxb                               JAXB plugin                                     2.3.0.1
jdk-tool                           Oracle Java SE Development Kit Installer Plugin 1.4
structs                            Structs Plugin                                  1.20
credentials                        Credentials Plugin                              2.3.0
workflow-step-api                  Pipeline: Step API                              2.20
script-security                    Script Security Plugin                          1.68
command-launcher                   Command Agent Launcher Plugin                   1.3
workflow-scm-step                  Pipeline: SCM Step                              2.9
apache-httpcomponents-client-4-api Apache HttpComponents Client 4.x API Plugin     4.5.10-2.0
ssh-credentials                    SSH Credentials Plugin                          1.18
jsch                               JSch dependency plugin                          0.1.55.1
git-client                         Git client plugin                               3.0.0
scm-api                            SCM API Plugin                                  2.6.3
display-url-api                    Display URL API                                 2.3.2
mailer                             Mailer Plugin                                   1.29
git                                Git plugin                                      4.0.0
jackson2-api                       Jackson 2 API Plugin                            2.10.0
workflow-api                       Pipeline: API                                   2.37
junit                              JUnit Plugin                                    1.28
token-macro                        Token Macro Plugin                              2.10
plain-credentials                  Plain Credentials Plugin                        1.5
slack                              Slack Notification Plugin                       2.34
bouncycastle-api                   bouncycastle API Plugin                         2.17
ldap                               LDAP Plugin                                     1.21
```

**Comment by casz** [comment] 2019-11-22 15:33
Clearly your going through a odd code path... Through the update center.

Please pre install plugins before attempting to use JCasC

**Comment by BrianSidebotham** [comment] 2019-11-22 16:07
Do you mean manually pre-install plugins - because I am pre-installing the plugins before attempting to use JCasC. It's just that they're installed via the `jenkins-cli`.

**Comment by BrianSidebotham** [comment] 2019-11-26 10:45
This problem was one of ordering - I already had the `jenkins.yaml` configuration in place when installing JCasC via the command line and this doesn't work. If I install JCasC via the command line without the YAML in place and then put `jenkins.yaml` in place and retstart Jenkins everything gets configured correctly. :+1:

**Comment by BrianSidebotham** [comment] 2019-11-28 13:56
Do you want to leaves this here as a bug report of `plugin cannot install properly from cli when YAML file is already present` ?

Or shall we close this ?

**Comment by casz** [comment] 2019-11-28 14:03
Not a bug we can solve in this plugin 😅
Not sure how you would solve it, it depends on install order when as I recall is A-Z.

**Comment by BrianSidebotham** [comment] 2019-11-28 14:17
What?

The issue is JSasC fails to install if `jenkins.yaml` is present. If `jenkins,yaml` is not present then it installs and I can restart Jenkins and then JSasC successfully processes `jenkins.yaml`

I guess from your quip remarks that you're not really interested though.

**Comment by casz** [comment] 2019-11-28 14:19
quip?

I was genuinely answering your question.
In anycase you ask jenkins cli to install a list of plugin.
What if you wait with installing JCasC last?
Perhaps not all plugins are loaded some do require a restart before activating plugins.

**Comment by casz** [comment] 2019-11-28 14:24
I tried to update the post about installation order of plugins to better explain the problem. As I said this is not a problem for JCasC to solve as we do not want to manage plugin state.

**Comment by BrianSidebotham** [comment] 2019-11-28 15:19
I am *not* asking Jenkins to install a list of plugins. *just* the JCasC plugin - all other plugins are already installed and deployed.

In each case, all other plugins are already installed and deployed.

If `jenkins.yaml` is in place and I then install JCasC (It is always installed last) it fails with the above stacktrace. If however, I do everything in exactly the same manor, but without `jenkins.yaml` in place JCasC installs correctly and then I can put `jenkins.yaml` in place after JCasC has been installed, restart Jenkins and JCasC correctly configures Jenkins. :+1:

This is not a plugin installation ordering issue.

**Comment by casz** [comment] 2019-11-28 15:26
Thanks for explaining the exact situation. 

It's definitely a plugin state issue.

The issue is located when extension loaded and are augmented.

@oleg-nenashev is there a way to retrigger extension augmentation on plugin?

**Comment by BrianSidebotham** [comment] 2019-11-28 15:29
No problem. Apologies for the frustration of cross wires. I know this was not the original description of this issue.

**Comment by casz** [comment] 2019-11-28 16:31
No worries :)

Now that I think about the issue. I believe there is no way to fix this issue.

As for EXTENSIONS_AUGMENTED there is no referenced besides inside the boot sequence here:
https://github.com/jenkinsci/jenkins/blob/eedf2a4e2a25f5883d828f22c2429ceebe2bd157/core/src/main/java/jenkins/model/Jenkins.java#L3201

So the install, shutdown jenkins, add jenkins.yml, start jenkins seems to be the order of steps that need to happen for the extension to be loaded inside Credentials, see the code located here: https://github.com/jenkinsci/credentials-plugin/blob/b5c54149deaf6036bdbcec66bf6906bb3c0b5a1a/src/main/java/com/cloudbees/plugins/credentials/casc/CredentialsRootConfigurator.java#L52
```java
@Extension(optional = true, ordinal = 2)
```

if you were to remove the `optional = true` then Credential plugin would fail to be loaded because it now has a none optional dependency to JCasC

**Comment by casz** [comment] 2019-11-28 16:35
@BrianSidebotham here are some better options for installing plugins ahead of time:

https://github.com/jenkinsci/docker/blob/master/install-plugins.sh
See doc on how to use [`install-plugins.sh`](https://github.com/jenkinsci/docker#preinstalling-plugins)

https://github.com/jenkinsci/custom-war-packager
https://github.com/jenkinsci/plugin-installation-manager-tool
https://docs.ansible.com/ansible/latest/modules/jenkins_plugin_module.html

**Comment by casz** [comment] 2020-02-26 20:29
I believe this is actually fixed in recent version of Jenkins core, after plugin loading it seems that load extensions gets called.

**Closed** 2020-03-07 14:17 UTC
Labels: bug
