### ISSUE TITLE
Missing key fields

### ISSUE THREAD

**Issue by asiekkowa** [jenkinsci/configuration-as-code-plugin#1142] opened 2019-10-10 13:05 UTC
### Your checklist for this issue

- [x ] Jenkins version
Jenkins ver. 2.192
- [x ] Plugin version
1.29
- [ x] OS
docker image: jenkins/jenkins:2.192-slim

### Description
Plugin does not save all required information.
Examples: 
1. 
https://wiki.jenkins-ci.org/display/JENKINS/Kubernetes+Plugin version 1.18.3
![image](https://user-images.githubusercontent.com/22298133/66570806-97f73000-eb6e-11e9-98b6-8349a994ab86.png)
fields _working directory_ and _command to run_  
- >therefore builds are not able to start

2.
https://github.com/jenkinsci/sonar-quality-gates-plugin/blob/master/README.md version 1.3.1
![image](https://user-images.githubusercontent.com/22298133/66570900-cd038280-eb6e-11e9-9de4-64b9a7802ff0.png)
field _token_ is not saved
-> therefore Jenkins instance is not able to start
--

**Comment by oleg-nenashev** [comment] 2019-10-11 09:44
Please reports separate JCasC compatibility issues to the respective plugins.

**Comment by oleg-nenashev** [comment] 2019-10-11 09:44
FTR https://wiki.jenkins.io/display/JENKINS/Plugins+compatibility+with+Jenkins+Configuration-as-Code+plugin#PluginscompatibilitywithJenkinsConfiguration-as-Codeplugin-Reportingissues

**Comment by asiekkowa** [comment] 2019-10-11 13:58
I have checked that problem is with 'configuration-as-code-plugin' - it **does not save the empty fields**. (And if such fields are not set by CasC plugin, kubernetes plugin takes default values.)

But when I added manually required values (args ans command),
```
- containers:
        - alwaysPullImage: false
          args: ""
          command: ""
          image: "jnlp-ansible:3.29.1"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jnlp"
```
kubernetes-plugin works perfectly.

**Comment by casz** [comment] 2019-10-11 15:04
This is not a bug in configuration as code. This is a bug in the plugin. They are not handling data bindings correctly.

**Comment by casz** [comment] 2019-10-11 15:10
Looking at the code
https://github.com/jenkinsci/sonar-quality-gates-plugin/blob/b87a0987c2b91ef63f5c6dd0f7a6839e341b3584/src/main/java/org/quality/gates/jenkins/plugin/GlobalConfig.java#L49

They are manually passing JSON data, this does not following coding standards setup by Jenkins plugin development. 

See this for reference
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md#step-5

**Comment by timja** [comment] 2020-01-01 12:24
Closing as separate issues should be reported to each individual plugin 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2020-01-01 12:23 UTC
Labels: plugin-compatibility
