### ISSUE TITLE
Configuration of administrativemonitorsconfiguration

### ISSUE THREAD

**Issue by savujevi** [jenkinsci/configuration-as-code-plugin#858] opened 2019-04-24 07:58 UTC
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- 2.174 [x] Jenkins version

-  1.12 [x] Plugin version

- Linux RHEL [x] OS

### Description

Hello developers,

could you please give me an example how to configure "administrativemonitorsconfiguration".

Thank you for your support.

Best regards,
    Sascha Vujevic

**Comment by casz** [comment] 2019-04-24 08:28
@savujevi you can't, next time use the search feature: https://github.com/jenkinsci/configuration-as-code-plugin/search?q=administrativemonitorsconfiguration+is%3Aissue&type=Issues

duplicate of #774

**Comment by casz** [comment] 2019-04-24 08:28
duplicate of #774

**Closed by casz** 2019-04-24 08:28 UTC

**Comment by savujevi** [comment] 2019-04-24 08:39
I had seen the other issue. I had expected to configure it because it is mentioned under https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/images/unclassified.png under unclassified.
Thanks for your patience.
