### ISSUE TITLE
numerous "can't handle type" warnings

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#536] opened 2018-09-18 22:19 UTC
```
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class hudson.model.ViewProperty
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class hudson.model.ViewProperty
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class hudson.model.ViewProperty
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class hudson.model.ViewProperty
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class org.jenkinsci.plugins.matrixauth.AuthorizationMatrixNodeProperty
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class jenkins.branch.MultiBranchProjectViewHolder$ViewImpl
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class jenkins.branch.OrganizationFolderViewHolder$ViewImpl
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class org.jenkinsci.plugins.matrixauth.AuthorizationMatrixNodeProperty
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class org.jenkinsci.plugins.matrixauth.AuthorizationMatrixNodeProperty
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class jenkins.plugins.git.AbstractGitSCMSource$SpecificRevisionBuildChooser
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class hudson.plugins.git.GitChangeSet
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class jenkins.plugins.git.traits.BranchDiscoveryTrait$BranchSCMHeadAuthority
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class org.jenkinsci.plugins.github_branch_source.BranchDiscoveryTrait$BranchSCMHeadAuthority
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class org.jenkinsci.plugins.github_branch_source.OriginPullRequestDiscoveryTrait$OriginChangeRequestSCMHeadAuthority
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class org.jenkinsci.plugins.github_branch_source.TagDiscoveryTrait$TagSCMHeadAuthority
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class jenkins.plugins.git.traits.TagDiscoveryTrait$TagSCMHeadAuthority
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class hudson.plugins.git.GitChangeSet
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class hudson.plugins.git.SubmoduleConfig
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class hudson.plugins.git.GitChangeSet
jenkins_1  | Sep 18, 2018 10:06:35 PM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
jenkins_1  | WARNING: Configuration-as-Code can't handle type class jenkins.plugins.git.AbstractGitSCMSource$SpecificRevisionBuildChooser
```

not sure if this is expected behavior or a bug?

**Comment by ndeloof** [comment] 2018-09-20 15:04
do you encounter this doing an export ? I won't be surprise the jenkins => yaml path hits many components we don't support (yet) so this would just be noise, but not a blocker. In another context this would be a way more annoying news.

**Comment by rtyler** [comment] 2018-09-20 16:30
I just ran export again on my demo instance and idn't see the expected warnings to show up. So perhaps it's not that.. :frowning:

**Comment by ewelinawilkosz** [comment] 2018-09-20 16:54
Startup I think, reload for sure

**Comment by batmat** [comment] 2019-01-30 09:46
FWIW, we do have many of these warnings in Evergreen logs in Sentry. But I need to double-check if they're coming from actually up to date instances or not.

**Comment by timja** [comment] 2019-04-30 10:04
@batmat are you still seeing these in sentry?
Don't think I see this on my instances

**Comment by timja** [comment] 2019-04-30 19:08
Still happens when viewing the JSON schema

**Comment by reinholdfuereder** [comment] 2019-05-29 04:46
In our rather limited JCasC usage we currently have just one warning:
```
WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class jenkins.security.plugins.ldap.LDAPConfiguration#extraEnvVars: type is abstract but not Describable.
```
=> Not sure if that really fits here as well, because it says "Can't handle class" instead of "can't handle type"...

**Comment by casz** [comment] 2019-05-29 05:02
Could you please include context, what are you configure?

**Comment by reinholdfuereder** [comment] 2019-05-29 07:27
@casz Oops, sorry, the context is LDAP configuration via:
```
  securityRealm:
    ldap:
      cache:
        size: 50
        ttl: 60
      configurations:
        - server: ***
          rootDN: ***
          managerDN: ***
          managerPasswordSecret: ***
          userSearchBase: ***
          userSearch: ***
          groupSearchBase: ***
```

**Comment by ndeloof** [comment] 2019-05-29 08:56
The actual property to use with JCasC is `environmentProperty` 
https://github.com/jenkinsci/ldap-plugin/blob/master/src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java#L374
This warning can be ignored it's not relevant in this specific context (but helps us detect plugin misconception in other context)

**Comment by timja** [comment] 2019-05-29 09:00
Is the problem that the setter is restricted but not the getter? not quite seeing why its logging that error, its just a map of string to string?

**Comment by ndeloof** [comment] 2019-05-29 09:06
Being Restricted we should skip this property and not show such a warning, so there's a fix needed here. This is a false positive we can avoid

**Comment by reinholdfuereder** [comment] 2019-05-29 11:15
(Yes, I don't need/want to configure the "environment properties")

**Comment by ndeloof** [comment] 2019-05-29 14:09
Maybe we should just ignore any `Map` attribute as those aren't supported

**Comment by timja** [comment] 2019-05-29 14:10
Any reason we can't support them?
Or is it just we want Pojo's for typing and schema generation?

**Comment by ndeloof** [comment] 2019-05-29 14:53
@timja early prototype did support yaml Maps, but this demonstrated being very confusing for users. So we decided to only support a minimal readable subset of yaml syntax.

**Comment by reinholdfuereder** [comment] 2019-06-04 14:28
@ndeloof @timja and @casz Thanks for the extremely quick fix!

**Comment by reinholdfuereder** [comment] 2019-06-19 11:45
I dare to get on your nerves another time ;-)

After adding some more JCasC configurations (in comparison to before/above), I am now getting (only) the following warning during Jenkins startup (twice):
```
WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class jenkins.scm.impl.subversion.SubversionSCMSource#owner: type is abstract but not Describable.
```

I am pretty sure the JCasC context is the configuration of a "global library": this is the interesting parts of the "jenkins.yaml" file:
```
jenkins:
  ...

  securityRealm:
    ldap:
      ...

credentials:
  system:
    domainCredentials:
    - credentials:
      ...
      - usernamePassword:
          scope: GLOBAL
          id: jenkins-ldap
          username: ***
          password: ***
          description: "Jenkins LDAP user and password credentials"
      ...

unclassified:
  ...
  globalLibraries:
    libraries:
    - name: "acme-shared-library"
      defaultVersion: "trunk"
      allowVersionOverride: true
      includeInChangesets: false
      retriever:
        modernSCM:
          scm:
            subversion:
              remoteBase: "https://<SVN PATH>/"
              credentialsId: jenkins-ldap
  ...
```

These are all Jenkins logs relevant for this warning or the "global library" configuration (please mind but ignore the duplicate logging or are these maybe even temporary duplicate configuration object instantiations: this is another issue => #899):
```
...
2019-06-11 10:06:43.572+0000 [id=35]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class org.jenkinsci.plugins.workflow.libs.LibraryConfiguration.name = acme-shared-library
2019-06-11 10:06:43.576+0000 [id=35]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class jenkins.scm.impl.subversion.SubversionSCMSource.remoteBase = https://<SVN PATH>/
2019-06-11 10:06:43.577+0000 [id=35]    WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class jenkins.scm.impl.subversion.SubversionSCMSource#owner: type is abstract but not Describable.
2019-06-11 10:06:43.578+0000 [id=35]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting jenkins.scm.impl.subversion.SubversionSCMSource{id='4b43e974-7f07-4a35-9646-da9361bd0127'}.credentialsId = jenkins-ldap
2019-06-11 10:06:43.578+0000 [id=35]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.scm = {subversion={}}
2019-06-11 10:06:43.579+0000 [id=35]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class org.jenkinsci.plugins.workflow.libs.LibraryConfiguration.retriever = {modernSCM={}}
2019-06-11 10:06:43.579+0000 [id=35]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting org.jenkinsci.plugins.workflow.libs.LibraryConfiguration@40045ff7.allowVersionOverride = true
2019-06-11 10:06:43.580+0000 [id=35]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting org.jenkinsci.plugins.workflow.libs.LibraryConfiguration@40045ff7.defaultVersion = trunk
2019-06-11 10:06:43.580+0000 [id=35]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting org.jenkinsci.plugins.workflow.libs.LibraryConfiguration@40045ff7.includeInChangesets = false
...
2019-06-11 10:06:45.472+0000 [id=35]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class org.jenkinsci.plugins.workflow.libs.LibraryConfiguration.name = acme-shared-library
2019-06-11 10:06:45.474+0000 [id=35]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class jenkins.scm.impl.subversion.SubversionSCMSource.remoteBase = https://<SVN PATH>/
2019-06-11 10:06:45.474+0000 [id=35]    WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class jenkins.scm.impl.subversion.SubversionSCMSource#owner: type is abstract but not Describable.
2019-06-11 10:06:45.475+0000 [id=35]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting jenkins.scm.impl.subversion.SubversionSCMSource{id='32242226-c66e-4032-9067-6e5bd9ee2db9'}.credentialsId = jenkins-ldap
2019-06-11 10:06:45.475+0000 [id=35]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.scm = {subversion={}}
2019-06-11 10:06:45.475+0000 [id=35]    INFO    i.j.p.c.i.c.DataBoundConfigurator#tryConstructor: Setting class org.jenkinsci.plugins.workflow.libs.LibraryConfiguration.retriever = {modernSCM={}}
2019-06-11 10:06:45.476+0000 [id=35]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting org.jenkinsci.plugins.workflow.libs.LibraryConfiguration@1a7cac19.allowVersionOverride = true
2019-06-11 10:06:45.476+0000 [id=35]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting org.jenkinsci.plugins.workflow.libs.LibraryConfiguration@1a7cac19.defaultVersion = trunk
2019-06-11 10:06:45.476+0000 [id=35]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting org.jenkinsci.plugins.workflow.libs.LibraryConfiguration@1a7cac19.includeInChangesets = false
2019-06-11 10:06:45.477+0000 [id=35]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting org.jenkinsci.plugins.workflow.libs.GlobalLibraries@1a129020.libraries = [org.jenkinsci.plugins.workflow.libs.LibraryConfiguration@1a7cac19]
2019-06-11 10:06:45.506+0000 [id=35]    INFO    i.jenkins.plugins.casc.Attribute#setValue: Setting jenkins.model.GlobalConfigurationCategory$Unclassified@42736d5a.globalLibraries = org.jenkinsci.plugins.workflow.libs.GlobalLibraries@1a129020
...
```

**Comment by reinholdfuereder** [comment] 2019-10-11 06:29
It seems that after updating JCasC plugin from 1.31 to 1.32 a similar warning appears during Jenkins startup that was not there before:
`2019-10-10 14:56:50.519+0000 [id=119]   WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration#metaClass: type is abstract but not Describable.`

(Job DSL plugin is installed in version 1.76 since ~ end of August)

**Unfortunately it (the plugin update as root cause) does not make fully sense though, as the warning did not appear right after first startup after plugin update.** And I updated a few other plugins at the same time (e.g. "script-security" from 1.64 to 1.66) and about 10h before Jenkins core from 2.198 to 2.199... And changed the job DSL usage in JCasC configuration also about at the same time as the Jenkins core upgrade...

Actually, according to the Jenkins logs:
```
...
2019-10-10 04:48:14.488+0000 [id=29]    INFO    hudson.PluginManager#loadDetachedPlugins: Upgrading Jenkins. The last running version was 2.198. This Jenkins is version 2.199.
2019-10-10 04:48:14.532+0000 [id=29]    INFO    hudson.PluginManager#loadDetachedPlugins: Upgraded Jenkins from version 2.198 to version 2.199. Loaded detached plugins (and dependencies): []
...
2019-10-10 04:48:47.404+0000 [id=23]    INFO    hudson.WebAppMain$3#run: Jenkins is fully up and running
...
2019-10-10 14:50:14.283+0000 [id=82]    INFO    h.m.UpdateCenter$UpdateCenterConfiguration#download: Downloading configuration-as-code
---> Plugins installed:
        script-security:1.66
        docker-workflow:1.21
        pam-auth:1.6
        email-ext:2.68
        htmlpublisher:1.21
        mailer:1.29
        ssh-credentials:1.18
        configuration-as-code:1.32
---> Initializing Jenkins restart after plugin installation!
2019-10-10 14:50:14.856+0000 [id=30]    INFO    j.util.groovy.GroovyHookScript#execute: Executing /var/lib/jenkins/init.groovy.d/03-basics.groovy
2019-10-10 14:50:14.869+0000 [id=86]    INFO    jenkins.model.Jenkins$23#run: Restart in 10 seconds
--> Jenkins restart is pending: skipping this hook script
2019-10-10 14:50:14.897+0000 [id=30]    INFO    jenkins.InitReactorRunner$1#onAttained: Completed initialization
2019-10-10 14:50:14.928+0000 [id=23]    INFO    hudson.WebAppMain$3#run: Jenkins is fully up and running
2019-10-10 14:50:24.869+0000 [id=86]    INFO    jenkins.model.Jenkins$23#run: Restarting VM as requested by SYSTEM
2019-10-10 14:50:24.870+0000 [id=86]    INFO    jenkins.model.Jenkins#cleanUp: Stopping Jenkins
2019-10-10 14:50:24.880+0000 [id=86]    INFO    jenkins.model.Jenkins$18#onAttained: Started termination
2019-10-10 14:50:24.900+0000 [id=86]    INFO    jenkins.model.Jenkins$18#onAttained: Completed termination
2019-10-10 14:50:24.900+0000 [id=86]    INFO    jenkins.model.Jenkins#_cleanUpDisconnectComputers: Starting node disconnection
2019-10-10 14:50:25.046+0000 [id=86]    INFO    jenkins.model.Jenkins#_cleanUpShutdownPluginManager: Stopping plugin manager
2019-10-10 14:50:25.059+0000 [id=86]    INFO    jenkins.model.Jenkins#_cleanUpPersistQueue: Persisting build queue
2019-10-10 14:50:25.101+0000 [id=86]    INFO    jenkins.model.Jenkins#_cleanUpAwaitDisconnects: Waiting for node disconnection completion
2019-10-10 14:50:25.101+0000 [id=86]    INFO    jenkins.model.Jenkins#cleanUp: Jenkins stopped
...
2019-10-10 14:50:45.437+0000 [id=23]    INFO    hudson.WebAppMain$3#run: Jenkins is fully up and running
...
2019-10-10 14:51:46.712+0000 [id=19]    INFO    hudson.PluginManager#install: Starting installation of a batch of 5 plugins plus their dependencies
2019-10-10 14:51:47.569+0000 [id=112]   INFO    h.model.UpdateCenter$DownloadJob#run: Starting the installation of xunit on behalf of r.fuereder
2019-10-10 14:51:48.189+0000 [id=112]   INFO    h.m.UpdateCenter$UpdateCenterConfiguration#download: Downloading xunit
2019-10-10 14:51:48.330+0000 [id=112]   INFO    h.model.UpdateCenter$DownloadJob#run: Starting the installation of windows-slaves on behalf of r.fuereder
2019-10-10 14:51:48.914+0000 [id=112]   INFO    h.m.UpdateCenter$UpdateCenterConfiguration#download: Downloading windows-slaves
2019-10-10 14:51:49.108+0000 [id=112]   INFO    h.model.UpdateCenter$DownloadJob#run: Starting the installation of github on behalf of r.fuereder
2019-10-10 14:51:49.682+0000 [id=112]   INFO    h.m.UpdateCenter$UpdateCenterConfiguration#download: Downloading github
2019-10-10 14:51:50.323+0000 [id=112]   INFO    h.model.UpdateCenter$DownloadJob#run: Starting the installation of jackson2-api on behalf of r.fuereder
2019-10-10 14:51:50.892+0000 [id=112]   INFO    h.m.UpdateCenter$UpdateCenterConfiguration#download: Downloading jackson2-api
2019-10-10 14:51:51.439+0000 [id=112]   INFO    h.model.UpdateCenter$DownloadJob#run: Starting the installation of apache-httpcomponents-client-4-api on behalf of r.fuereder
2019-10-10 14:51:52.019+0000 [id=112]   INFO    h.m.UpdateCenter$UpdateCenterConfiguration#download: Downloading apache-httpcomponents-client-4-api
...
2019-10-10 14:52:25.118+0000 [id=23]    INFO    hudson.WebAppMain$3#run: Jenkins is fully up and running
...
2019-10-10 14:56:50.449+0000 [id=119]   WARNING hudson.util.Secret#toString: Use of toString() on hudson.util.Secret from hudson.util.Secret$1.convert(Secret.java:306). Prefer getPlainText() or getEncryptedValue() depending your needs. see ht
tps://jenkins.io/redirect/hudson.util.Secret/
2019-10-10 14:56:50.454+0000 [id=119]   WARNING hudson.util.Secret#toString: Use of toString() on hudson.util.Secret from hudson.util.Secret$1.convert(Secret.java:306). Prefer getPlainText() or getEncryptedValue() depending your needs. see ht
tps://jenkins.io/redirect/hudson.util.Secret/
2019-10-10 14:56:50.454+0000 [id=119]   WARNING hudson.util.Secret#toString: Use of toString() on hudson.util.Secret from org.apache.commons.beanutils.converters.AbstractConverter.convertToString(AbstractConverter.java:195). Prefer getPlainTe
xt() or getEncryptedValue() depending your needs. see https://jenkins.io/redirect/hudson.util.Secret/
2019-10-10 14:56:50.457+0000 [id=119]   WARNING hudson.util.Secret#toString: Use of toString() on hudson.util.Secret from hudson.util.Secret$1.convert(Secret.java:306). Prefer getPlainText() or getEncryptedValue() depending your needs. see ht
tps://jenkins.io/redirect/hudson.util.Secret/
2019-10-10 14:56:50.457+0000 [id=119]   WARNING hudson.util.Secret#toString: Use of toString() on hudson.util.Secret from org.apache.commons.beanutils.converters.AbstractConverter.convertToString(AbstractConverter.java:195). Prefer getPlainTe
xt() or getEncryptedValue() depending your needs. see https://jenkins.io/redirect/hudson.util.Secret/
2019-10-10 14:56:50.459+0000 [id=119]   WARNING hudson.util.Secret#toString: Use of toString() on hudson.util.Secret from hudson.util.Secret$1.convert(Secret.java:306). Prefer getPlainText() or getEncryptedValue() depending your needs. see ht
tps://jenkins.io/redirect/hudson.util.Secret/
2019-10-10 14:56:50.459+0000 [id=119]   WARNING hudson.util.Secret#toString: Use of toString() on hudson.util.Secret from org.apache.commons.beanutils.converters.AbstractConverter.convertToString(AbstractConverter.java:195). Prefer getPlainTe
xt() or getEncryptedValue() depending your needs. see https://jenkins.io/redirect/hudson.util.Secret/
2019-10-10 14:56:50.480+0000 [id=119]   WARNING hudson.util.Secret#toString: Use of toString() on hudson.util.Secret from hudson.util.Secret$1.convert(Secret.java:306). Prefer getPlainText() or getEncryptedValue() depending your needs. see ht
tps://jenkins.io/redirect/hudson.util.Secret/
2019-10-10 14:56:50.481+0000 [id=119]   WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class jenkins.security.plugins.ldap.FromGroupSearchLDAPGroupMembershipStrategy#authoritiesPopulator: type is abstract but not Describabl
e.
2019-10-10 14:56:50.519+0000 [id=119]   WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration#metaClass: type is abstract but not Describable.
2019-10-10 14:56:50.710+0000 [id=119]   WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class jenkins.scm.impl.subversion.SubversionSCMSource#owner: type is abstract but not Describable.
...
```
**... it seems as if the first time was caused by going to "Manage Jenkins > Configuration as Code" and then "View configuration"!?**
```
$ grep "Can't handle class javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration" /var/log/jenkins/jenkins.log
2019-10-10 14:56:50.519+0000 [id=119]   WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration#metaClass: type is abstract but not Describable.
2019-10-11 04:34:36.361+0000 [id=35]    WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration#metaClass: type is abstract but not Describable.
2019-10-11 04:34:40.194+0000 [id=35]    WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration#metaClass: type is abstract but not Describable.
2019-10-11 04:39:59.751+0000 [id=45]    WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration#metaClass: type is abstract but not Describable.
2019-10-11 04:40:02.857+0000 [id=45]    WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration#metaClass: type is abstract but not Describable.

$ grep "Can't handle class javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration" /var/log/jenkins/jenkins.log.1
# Nothing
```

(Sorry for this rather weird comment due to trying to give the full picture from the top of my head)

**Comment by timja** [comment] 2019-10-11 06:50
It will be nothing to do with the plugin update, it's just caused by exporting the configuration  or viewing the reference docs

**Comment by reinholdfuereder** [comment] 2019-10-11 11:08
@timja that sounds reasonable; the weird thing is that it looks like it started when I was viewing the current JCasC configuration, but/and it is since then always logged during Jenkins restart as well...

**Comment by reinholdfuereder** [comment] 2019-10-16 09:56
New Jenkins Lockable Resources plugin release v2.6 thankfully also supports JCasC now =>
```
2019-10-16 09:50:27.953+0000 [id=76]    WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class org.jenkins.plugins.lockableresources.LockableResource#build: type is abstract but not Describable.
```

By the way: Is adding such comments helpful at all (to you/anyone)? Or is it just feeling like unnecessary spam?

**Comment by timja** [comment] 2019-10-16 10:10
> New Jenkins Lockable Resources plugin release v2.6 thankfully also supports JCasC now =>
> 
> ```
> 2019-10-16 09:50:27.953+0000 [id=76]    WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class org.jenkins.plugins.lockableresources.LockableResource#build: type is abstract but not Describable.
> ```
> 
> By the way: Is adding such comments helpful at all (to you/anyone)? Or is it just feeling like unnecessary spam?

Useful for whomever finds the time to look at it.

**Comment by casz** [comment] 2020-01-14 10:54
I think we can mostly close this? the topic is too broad and we need specific plugins.

**Comment by reinholdfuereder** [comment] 2020-01-14 12:41
@casz Presumably you are right; although it might be interesting which warnings are still "alive"/around? In my case only these (anymore):
```
WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration#metaClass: type is abstract but not Describable.
WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class jenkins.scm.impl.subversion.SubversionSCMSource#owner: type is abstract but not Describable.
WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class org.jenkins.plugins.lockableresources.LockableResource#build: type is abstract but not Describable.
```

**Comment by reinholdfuereder** [comment] 2020-04-14 05:31
@jetersen Because the "stale" bot wants to close this issue (one again) and you wrote in https://github.com/jenkinsci/configuration-as-code-plugin/issues/536#issuecomment-574118007 "_I think we can mostly close this? the topic is too broad and we need specific plugins._":

* Job-DSL: I have not found a potentially matching issue yet. Should I file one (for the plugin)?
* SVN: Maybe a comment for JENKINS-54782 might be appropriate: should I add one? (However, I guess chances are rather slim that someone will fix that?)
* Lockable Resources: I have not found a potentially matching issue yet. Should I file one (for the plugin)?

**Comment by jetersen** [comment] 2020-04-14 06:02
Yes, please check the label: `jcasc-compatability`
See this dashboard to view existing one: [JCasC - Open Compatibility Issues](https://issues.jenkins-ci.org/secure/Dashboard.jspa?selectPageId=18341)
If the plugin uses GitHub issue report it there otherwise report it on https://issues.jenkins-ci.org

**Closed by jetersen** 2020-04-14 06:02 UTC
